# apiVersion: v1
# kind: Namespace
# metadata:
#   name: cs3219
#   labels:
#     app: cs3219
# spec:
#   ports:
#     - port: 80
#       name: web
#   clusterIP: None
#   selector:
#     app: cs3219-db

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cs3219-db
  namespace: cs3219
  labels:
    app: cs3219-db
spec:
  serviceName: cs3219-db
  replicas: 1
  selector:
    matchLabels:
      app: cs3219-db
  template:
    metadata:
      labels:
        app: cs3219-db
    spec:
      containers:
        - name: cs3219-db
          image: cs3219/mariadb:1.0.0
          ports:
            - containerPort: 3306
            # number: 3306
          env:
            - name: MYSQL_DATABASE
              value: cs3219
            - name: MYSQL_ROOT_PASSWORD
              value: password

  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
